# Generated by Django 5.2.7 on 2025-10-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plain_body',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='wp.pl', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
