# Generated by Django 5.2.7 on 2025-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_plain_body_article_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
